import type { BiddingPayload } from './bidding-types';

export const BIDDING_SAMPLE: BiddingPayload = {
  syncedAt: Date.now(),
  project: {
    name: '800 Brady Ave',
    location: 'Bronx, NY 10462',
    id: '800-BRDY-2025',
    phase: 'Bidding',
    coordInitials: 'Sol',
    coordName: 'Shlomo Friedman',
    trades: [
      { trade: 'Controlled Inspections', annot: null, subs: [{ name: 'Signia', amount: 74500, status: 'rec' }, { name: 'ny testing', amount: 95000, status: 'rec' }], low: 74500 },
      { trade: 'DOT Meeting', annot: null, subs: [{ name: 'Quiver', amount: null, status: 'snt' }], low: null },
      { trade: 'Pre-construction', annot: null, subs: [], low: null },
      { trade: 'Live security', annot: null, subs: [{ name: 'City Wide', amount: 8800, status: 'rec' }, { name: 'Monitex', amount: 14050, status: 'rec' }], low: 8800 },
      { trade: 'Superintendent', annot: null, subs: [{ name: 'Mod', amount: null, status: 'rec' }, { name: 'Home Core', amount: null, status: 'snt' }], low: null },
      { trade: 'Site Safety Plans', annot: null, subs: [{ name: 'MOD', amount: 2500, status: 'rec' }, { name: 'Zv Drafting', amount: null, status: 'snt' }], low: 2500 },
      { trade: 'Surveyor / Monitoring', annot: null, subs: [{ name: 'Quiver', amount: 35700, status: 'rec' }], low: 35700 },
      { trade: 'Fire Stopping', annot: null, subs: [{ name: 'A1', amount: null, status: 'rec' }], low: null },
      { trade: 'Pipe Seal', annot: null, subs: [{ name: 'A1', amount: 50790, status: 'rec' }, { name: 'Target Piping', amount: 56000, status: 'rec' }, { name: 'quality', amount: 61000, status: 'rec' }], low: 50790 },
      { trade: 'Construction Fence', annot: null, subs: [{ name: 'AFS', amount: 14680, status: 'rec' }, { name: 'QSF', amount: 15950, status: 'rec' }], low: 14680 },
      { trade: 'Foundation Waterproofing', annot: null, subs: [{ name: 'Drip Drop', amount: null, status: 'hld' }, { name: 'A1', amount: null, status: 'hld' }], low: null },
      { trade: 'Excavation & Foundation Structure', annot: null, subs: [{ name: 'Prime', amount: 3030000, status: 'rec' }, { name: 'Elite Concrete', amount: 2865000, status: 'rec' }, { name: 'Edge', amount: null, status: 'ntb' }, { name: 'Greystone', amount: 2815665, status: 'rec' }], low: 2815665 },
      { trade: 'Steel', annot: null, subs: [{ name: 'CMC', amount: 22910, status: 'rec' }, { name: 'Candid', amount: 87810, status: 'rec' }], low: 22910 },
      { trade: 'Framer / Taping & Painting', annot: null, subs: [{ name: 'Hybrid', amount: 1950000, status: 'rec' }, { name: 'MTW', amount: 1686000, status: 'rec' }, { name: 'UGS', amount: 1805000, status: 'rec' }, { name: 'Blade', amount: null, status: 'fu1' }], low: 1686000 },
      { trade: 'Windows', annot: null, subs: [{ name: 'Silhouette', amount: 396027, status: 'rec' }, { name: 'Windows NYC', amount: 349000, status: 'rec' }, { name: 'slate', amount: 328500, status: 'rec' }, { name: 'Alumtec', amount: 404500, status: 'rec' }], low: 328500 },
      { trade: 'Main entrance door', annot: 'same sub as windows', subs: [], low: null },
      { trade: 'Roofer', annot: null, subs: [{ name: 'Pinnacle', amount: 257609, status: 'rec' }, { name: 'Master', amount: null, status: 'snt' }], low: 257609 },
      { trade: 'HVAC', annot: null, subs: [{ name: 'CMR', amount: 204000, status: 'rec' }, { name: 'DPS', amount: null, status: 'snt' }], low: 204000 },
      { trade: 'PTAC', annot: null, subs: [{ name: 'Volt', amount: 295836, status: 'rec' }], low: 295836 },
      { trade: 'Electrician', annot: null, subs: [{ name: 'EP Electric', amount: 920000, status: 'rec' }, { name: 'Bright Light', amount: null, status: 'fu2' }], low: 920000 },
      { trade: 'Fire Alarm', annot: null, subs: [{ name: 'Alert Fire Systems', amount: null, status: 'fu1' }, { name: 'SafeSite Alarm', amount: null, status: 'fu1' }], low: null },
      { trade: 'Low Voltage', annot: null, subs: [{ name: 'TechLink', amount: 133895, status: 'rec' }], low: 133895 },
      { trade: 'Scaffolding', annot: null, subs: [{ name: 'ACS', amount: 460000, status: 'rec' }, { name: 'Metro Scaffold', amount: null, status: 'snt' }], low: 460000 },
      { trade: 'Garbage Chute', annot: null, subs: [{ name: 'Apex Chute', amount: 33000, status: 'rec' }], low: 33000 },
      { trade: 'Stucco / waterproofing / coping', annot: null, subs: [{ name: 'Prestige Stucco', amount: 520669, status: 'rec' }, { name: 'NYC Facade', amount: null, status: 'snt' }], low: 520669 },
      { trade: 'Tiles', annot: null, subs: [{ name: 'Tri-State Tile', amount: 126549, status: 'rec' }, { name: 'FastFix', amount: null, status: 'snt' }], low: 126549 },
      { trade: 'Tile Installer', annot: null, subs: [{ name: 'Tile Pro', amount: 389162, status: 'rec' }], low: 389162 },
      { trade: 'Plumbing Fixtures', annot: null, subs: [{ name: 'PlumbRight', amount: 125659, status: 'rec' }], low: 125659 },
      { trade: 'Plumber / Sprinkler', annot: null, subs: [{ name: 'Northway Plumbing', amount: 1291350, status: 'rec' }, { name: 'AquaFire', amount: null, status: 'snt' }], low: 1291350 },
      { trade: 'Kitchens / Countertops', annot: null, subs: [{ name: 'CabinetWorks NYC', amount: 202390, status: 'rec' }, { name: 'TopChef Kitchens', amount: null, status: 'fu3' }], low: 202390 },
      { trade: 'Garage Door', annot: null, subs: [{ name: 'DoorMaster', amount: 13500, status: 'rec' }], low: 13500 },
      { trade: 'BPP', annot: null, subs: [{ name: 'BPP Direct', amount: 83957, status: 'rec' }], low: 83957 },
      { trade: 'Signage', annot: null, subs: [{ name: 'SignCraft NY', amount: 7885, status: 'rec' }], low: 7885 },
      { trade: 'Mailboxes', annot: null, subs: [{ name: 'MailPro', amount: 16658, status: 'rec' }], low: 16658 },
      { trade: 'Rubbish Removal', annot: null, subs: [{ name: 'Five Boro Carting', amount: 92400, status: 'rec' }, { name: 'Action Waste', amount: 261176, status: 'rec' }], low: 92400 },
      { trade: 'Elevator', annot: null, subs: [{ name: 'Otis Worldwide', amount: 578000, status: 'fnl' }], low: 578000 },
    ],
  },
  portfolioProjects: [
    { name: '800 Brady Ave', location: 'Bronx, NY 10462', isReal: true },
    { name: '3930 Carpenter', location: 'Bronx, NY', isReal: false },
    { name: '1923 Harrison', location: 'Bronx, NY', isReal: false },
    { name: '567 Maple', location: 'Brooklyn, NY', isReal: false },
    { name: '891 Oak', location: 'Brooklyn, NY', isReal: false },
    { name: '1450 Park', location: 'Manhattan, NY', isReal: false },
    { name: '2200 Bay', location: 'Queens, NY', isReal: false },
    { name: '7711 Bedford', location: 'Brooklyn, NY', isReal: false },
    { name: '4112 Bath', location: 'Brooklyn, NY', isReal: false },
    { name: '220 W 23rd', location: 'Manhattan, NY', isReal: false },
    { name: '512 Linden', location: 'Brooklyn, NY', isReal: false },
    { name: '1844 Marcy', location: 'Brooklyn, NY', isReal: false },
    { name: '2901 Snyder', location: 'Brooklyn, NY', isReal: false },
    { name: '115 Jay', location: 'Brooklyn, NY', isReal: false },
    { name: '940 Ralph', location: 'Brooklyn, NY', isReal: false },
    { name: '3300 Avenue J', location: 'Brooklyn, NY', isReal: false },
    { name: '210 E 87th', location: 'Manhattan, NY', isReal: false },
    { name: '708 Driggs', location: 'Brooklyn, NY', isReal: false },
    { name: '19 Throop', location: 'Brooklyn, NY', isReal: false },
    { name: '3500 Bedford', location: 'Brooklyn, NY', isReal: false },
    { name: '2710 Avenue K', location: 'Brooklyn, NY', isReal: false },
    { name: '402 Lefferts', location: 'Brooklyn, NY', isReal: false },
    { name: '1218 Atlantic', location: 'Brooklyn, NY', isReal: false },
    { name: '855 Foster', location: 'Brooklyn, NY', isReal: false },
    { name: '620 Empire', location: 'Brooklyn, NY', isReal: false },
    { name: '1011 Coney', location: 'Brooklyn, NY', isReal: false },
    { name: '77 Greene', location: 'Manhattan, NY', isReal: false },
    { name: '321 Crown', location: 'Brooklyn, NY', isReal: false },
    { name: '98 Patchen', location: 'Brooklyn, NY', isReal: false },
    { name: '444 Halsey', location: 'Brooklyn, NY', isReal: false },
    { name: '125 Lott', location: 'Brooklyn, NY', isReal: false },
    { name: '1733 Sterling', location: 'Brooklyn, NY', isReal: false },
    { name: '2204 Cortelyou', location: 'Brooklyn, NY', isReal: false },
    { name: '9 Marcus Garvey', location: 'Brooklyn, NY', isReal: false },
    { name: '488 Lincoln', location: 'Brooklyn, NY', isReal: false },
    { name: '230 St Marks', location: 'Brooklyn, NY', isReal: false },
    { name: '600 Bushwick', location: 'Brooklyn, NY', isReal: false },
    { name: '1100 DeKalb', location: 'Brooklyn, NY', isReal: false },
    { name: '35 Wyckoff', location: 'Queens, NY', isReal: false },
    { name: '1601 President', location: 'Brooklyn, NY', isReal: false },
    { name: '810 Quincy', location: 'Brooklyn, NY', isReal: false },
    { name: '41 Hancock', location: 'Brooklyn, NY', isReal: false },
    { name: '244 Decatur', location: 'Brooklyn, NY', isReal: false },
  ],
};
