import type { BudgetPayload } from './budget-types';

export const BUDGET_SAMPLE: BudgetPayload = {
  project: {
    name: '800 Brady Ave',
    location: 'Bronx, NY 10462',
    id: '800-BRDY-2025',
    phase: 'Budgeting',
    coordInitials: 'SK',
    coordName: 'Sol Klein',
    trades: [
      { trade: 'DOT meeting',                          est: 2500,    fin: null,       newv: 2500 },
      { trade: 'Fence',                                est: 28000,   fin: 14680,      newv: 14680 },
      { trade: 'Superintendent',                       est: 96000,   fin: null,       newv: 96000 },
      { trade: 'Site safety coordination',             est: 128000,  fin: null,       newv: null,    manual: true },
      { trade: 'Special inspector',                    est: 99000,   fin: 74500,      newv: 74500 },
      { trade: 'Survey',                               est: 25000,   fin: 35700,      newv: 35700 },
      { trade: 'Live Security',                        est: 17000,   fin: 8800,       newv: 8800 },
      { trade: 'Site Safety Plan',                     est: 5000,    fin: 2500,       newv: 2500 },
      { trade: 'fire extignitures',                    est: 5000,    fin: null,       newv: 5000 },
      { trade: 'Bathrooms',                            est: 14000,   fin: null,       newv: 14000 },
      { trade: 'Monitoring · vibration',               est: 27000,   fin: null,       newv: 27000 },
      { trade: 'Foundation',                           est: 600000,  fin: 2815665,    newv: 2815665 },
      { trade: 'Structure',                            est: 2420000, fin: 'INC',      newv: 'INC',   manual: true },
      { trade: 'Soil · Trucking',                      est: 150000,  fin: null,       newv: 150000 },
      { trade: 'Concrete LAB inspector',               est: 'INC',   fin: null,       newv: 'INC' },
      { trade: 'Plumbing · sprinkler',                 est: 1287000, fin: 1291350,    newv: 1291350 },
      { trade: 'Pipe insualtion',                      est: 'INC',   fin: 50790,      newv: 50790 },
      { trade: 'Elevator',                             est: 590000,  fin: 578000,     newv: 578000 },
      { trade: 'Windows',                              est: 275000,  fin: 328500,     newv: 328500 },
      { trade: 'Main doors',                           est: 'INC',   fin: null,       newv: 'INC' },
      { trade: 'Framing Exterior / Interior',          est: 1900000, fin: 1686000,    newv: 1686000 },
      { trade: 'Sheetrock',                            est: 'INC',   fin: 'INC',      newv: 'INC' },
      { trade: 'Tape / paint',                         est: 'INC',   fin: 'INC',      newv: 'INC' },
      { trade: 'Trimming · Doors',                     est: 'INC',   fin: 'INC',      newv: 'INC' },
      { trade: 'Fire Stopping',                        est: 'INC',   fin: 'INC',      newv: 'INC' },
      { trade: 'Insulation Exterior walls / interior', est: 'INC',   fin: 'INC',      newv: 'INC' },
      { trade: 'Watermain',                            est: 85000,   fin: null,       newv: 85000 },
      { trade: 'Hoist',                                est: 190000,  fin: 'INC',      newv: 'INC' },
      { trade: 'Scaffold / Shed',                      est: 570000,  fin: 460000,     newv: 460000 },
      { trade: 'Chutes / Compactors',                  est: 38000,   fin: 33000,      newv: 33000 },
      { trade: 'Electric',                             est: 990000,  fin: 920000,     newv: 920000 },
      { trade: 'Lighting Material',                    est: 60000,   fin: 'INC',      newv: 'INC',   manual: true },
      { trade: 'Fire Alarm',                           est: 42000,   fin: 146250,     newv: 146250 },
      { trade: 'Low Voltage',                          est: 125000,  fin: 133895,     newv: 133895 },
      { trade: 'Roofing',                              est: 195000,  fin: 257609,     newv: 257609 },
      { trade: 'HVAC',                                 est: 225000,  fin: 204000,     newv: 204000 },
      { trade: 'Ptac units',                           est: 350000,  fin: 295836,     newv: 295836 },
      { trade: 'Steel',                                est: 80000,   fin: 22910,      newv: 22910 },
      { trade: 'Stucco',                               est: 570000,  fin: 520669,     newv: 520669 },
      { trade: 'Tiles',                                est: 180000,  fin: 126549,     newv: 126549 },
      { trade: 'Tiles Installation',                   est: 385000,  fin: 389162,     newv: 389162 },
      { trade: 'Plumbing Fixtures',                    est: 144000,  fin: 125659,     newv: 125659 },
      { trade: 'Bathtubs',                             est: 'INC',   fin: 'INC',      newv: 'INC' },
      { trade: 'Kitchens',                             est: 215000,  fin: 202390,     newv: 202390 },
      { trade: 'Apt appliances',                       est: 145000,  fin: null,       newv: 145000 },
      { trade: 'Garage Door',                          est: null,    fin: 13500,      newv: 13500 },
      { trade: 'BPP',                                  est: 125000,  fin: 83957,      newv: 83957 },
      { trade: 'Signs',                                est: 14000,   fin: 7885,       newv: 7885 },
      { trade: 'Mailbox',                              est: 20000,   fin: 16658,      newv: 16658 },
      { trade: 'Garbage Removal',                      est: 255000,  fin: 261176,     newv: 261176 },
      { trade: 'Parking stops and marking',            est: 8000,    fin: null,       newv: 8000 },
      { trade: 'Bike room',                            est: 2000,    fin: null,       newv: 2000 },
      { trade: 'Green roof',                           est: 'NA',    fin: null,       newv: 'NA' },
      { trade: 'GC Fee',                               est: 1000000, fin: null,       newv: 1000000 },
    ],
  },
  portfolioProjects: [
    { name: '800 Brady Ave',    loc: 'Bronx, NY 10462',  real: true },
    { name: '3930 Carpenter',   loc: 'Bronx, NY' },
    { name: '1923 Harrison',    loc: 'Bronx, NY' },
    { name: '567 Maple',        loc: 'Brooklyn, NY' },
    { name: '891 Oak',          loc: 'Brooklyn, NY' },
    { name: '1450 Park',        loc: 'Manhattan, NY' },
    { name: '2200 Bay',         loc: 'Queens, NY' },
    { name: '7711 Bedford',     loc: 'Brooklyn, NY' },
    { name: '4112 Bath',        loc: 'Brooklyn, NY' },
    { name: '220 W 23rd',       loc: 'Manhattan, NY' },
    { name: '512 Linden',       loc: 'Brooklyn, NY' },
    { name: '1844 Marcy',       loc: 'Brooklyn, NY' },
    { name: '2901 Snyder',      loc: 'Brooklyn, NY' },
    { name: '115 Jay',          loc: 'Brooklyn, NY' },
    { name: '940 Ralph',        loc: 'Brooklyn, NY' },
    { name: '3300 Avenue J',    loc: 'Brooklyn, NY' },
    { name: '210 E 87th',       loc: 'Manhattan, NY' },
    { name: '708 Driggs',       loc: 'Brooklyn, NY' },
    { name: '19 Throop',        loc: 'Brooklyn, NY' },
    { name: '3500 Bedford',     loc: 'Brooklyn, NY' },
    { name: '2710 Avenue K',    loc: 'Brooklyn, NY' },
    { name: '402 Lefferts',     loc: 'Brooklyn, NY' },
    { name: '1218 Atlantic',    loc: 'Brooklyn, NY' },
    { name: '855 Foster',       loc: 'Brooklyn, NY' },
    { name: '620 Empire',       loc: 'Brooklyn, NY' },
    { name: '1011 Coney',       loc: 'Brooklyn, NY' },
    { name: '77 Greene',        loc: 'Manhattan, NY' },
    { name: '321 Crown',        loc: 'Brooklyn, NY' },
    { name: '98 Patchen',       loc: 'Brooklyn, NY' },
    { name: '444 Halsey',       loc: 'Brooklyn, NY' },
    { name: '125 Lott',         loc: 'Brooklyn, NY' },
    { name: '1733 Sterling',    loc: 'Brooklyn, NY' },
    { name: '2204 Cortelyou',   loc: 'Brooklyn, NY' },
    { name: '9 Marcus Garvey',  loc: 'Brooklyn, NY' },
    { name: '488 Lincoln',      loc: 'Brooklyn, NY' },
    { name: '230 St Marks',     loc: 'Brooklyn, NY' },
    { name: '600 Bushwick',     loc: 'Brooklyn, NY' },
    { name: '1100 DeKalb',      loc: 'Brooklyn, NY' },
    { name: '35 Wyckoff',       loc: 'Queens, NY' },
    { name: '1601 President',   loc: 'Brooklyn, NY' },
    { name: '810 Quincy',       loc: 'Brooklyn, NY' },
    { name: '41 Hancock',       loc: 'Brooklyn, NY' },
    { name: '244 Decatur',      loc: 'Brooklyn, NY' },
  ],
  syncedAt: Date.now(),
};
